W4D5/MusicApp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users
  resource :session, only: [:new, :create, :destroy]
  resources :bands

  root to: redirect('/session/new')
end

W4D5/MusicApp/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint(8)        not null, primary key
#  name       :string           not null
#  member_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord

  validates :name, optional: false

  belongs_to :band_member,
    primary_key: :id,
    foreign_key: :member_id,
    class_name: :User


end

W4D5/MusicApp/app/models/user.rb
require 'bcrypt'
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  username        :string           not null
#

class User < ApplicationRecord

  validates :username, presence: true, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :session_token, presence: true, uniqueness: true
  validates :password_digest, :email, presence: true

  after_initialize :ensure_session_token
  attr_reader :password, :password_digest

  # ===================================
  # ASSOCIATIONS
  # ===================================
  has_many :music_groups,
    primary_key: :id,
    foreign_key: :member_id,
    class_name: :Band


  # ===================================
  # CLASS METHODS
  # ===================================
  def self.generate_session_token
    @session_token ||= SecureRandom.urlsafe_base64
  end


  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)

    user && user.is_password?(password) ? user : nil
  end



  # ===================================
  # INSTANCE METHODS
  # ===================================

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    User.generate_session_token
    self.save!
    self.session_token
  end


end

W4D5/MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def current_user
    @user ||= User.find_by(session_token: session[:session_token])
  end

  def login!(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def logged_in?
    !!current_user
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
    @current_user = nil
  end

  def require_login
    redirect_to new_session_url unless logged_in?
  end

  def require_logout
    redirect_to users_url if logged_in?
  end

end

W4D5/MusicApp/app/controllers/bands_controller.rb
# bands     GET    /bands(.:format)                       bands#index
#           POST   /bands(.:format)                       bands#create
# new_band  GET    /bands/new(.:format)                   bands#new
# edit_band GET    /bands/:id/edit(.:format)              bands#edit
# band      GET    /bands/:id(.:format)                   bands#show
#           PATCH  /bands/:id(.:format)                   bands#update
#           PUT    /bands/:id(.:format)                   bands#update
#           DELETE /bands/:id(.:format)                   bands#destroy

class BandsController < ApplicationController

  def index
    @bands = Band.all
    render :index
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def new
    @band = Band.new
    render :new
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end

  def create

    @band = Band.new(band_params)

    if @band.save
      redirect_to bands_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def update
    @band = Band.find(params[:id])

    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      render json: @band.errors.full_messages, status: 422
    end
  end



  private

  def band_params
    name = band_params_name
    if name
      member_id = find_member_id(name['band_member_name'])
      params[:member_id] = member_id if member_id
    end
    params.require(:band).permit(:name, :member_id)
  end

  # band_member_name set in the _form.html.erb
  def band_params_name
    params.require(:band).permit(:band_member_name)
  end

  def find_member_id(username)
    member = User.find_by(username: username)
    member ? member.id : nil
  end

end

W4D5/MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  before_action :require_login, only: [:destroy]
  before_action :require_logout, only: [:new, :create]

  def new
    @user = User.new
    render :new
  end

  def create # login
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )
    if @user
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ['Invalid Login Credentials']
      render :new
    end
  end

  def destroy # logout
    logout!
    redirect_to new_session_url
  end

end

W4D5/MusicApp/app/controllers/users_controller.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  username        :string           not null
#
class UsersController < ApplicationController

  def index
    @users = User.all
    render :index
  end

  def edit
    @user = User.find(params[:id])
    render :edit
  end

  def new
    @user = User.new
    render :new
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to user_url(@user)
    else
      render json: @user.errors.full_messages, status: 422
    end
  end



  private
  def user_params
    params.require(:user).permit(:username, :password, :email)
  end
end

W4D5/MusicApp/app/helpers/application_helper.rb
module ApplicationHelper

  def authentication
    "
    <input
      type=\"hidden\"
      name=\"authenticity_token\"
      value=\"<#{ h(form_authenticity_token) }\"
      >
    ".html_safe
  end


  def user_interaction(user)
    if user
      "<a href=\"#{ h(user_url(user)) }\">Hello, #{ h(user.username) }</a>
      <form action=\"#{ session_url(user) }\" method=\"post\">
        #{ h(authentication) }
        <input type=\"hidden\" name=\"_method\" value=\"delete\">
        <input type=\"submit\" value=\"Logout!\">
      </form>
    ".html_safe
    else
      "<a href=\"#{new_user_url}\">Create New User</a>".html_safe
    end
  end
end

W4D5/MusicApp/app/helpers/bands_helper.rb
module BandsHelper
end

W4D5/MusicApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

W4D5/MusicApp/app/helpers/users_controller_helper.rb
module UsersControllerHelper
end

W4D5/MusicApp/app/views/bands/_form.html.erb
<% if type == :new %>
<% button_val = "Create!" %>
<% action_url = bands_url %>
<% elsif type == :edit %>
<% button_val = "Edit!" %>
<% action_url = band_url %>
<%elsif type == :login %>
<% button_val = "Login" %>
<% action_url = session_url %>
<% end %>


<form action="<%= action_url %>" method="post">
  <% if type == :edit %>
  <input type="hidden" name="_method" value="patch">
  <% end %>
  <%= authentication %>


  <label for='bandname'>Bandname:</label>
  <input type="text" id="name" name="band[name]"
  value="<%=band.name %>">
  <br>

  <label for="band_member_name">Band Member Name:</label>
  <input type="text" id="bane_member_name" name="band[band_member_name]">
  <br>

  <input type="submit" value="<%= button_val %>">

</form>

W4D5/MusicApp/app/views/bands/_user.html.erb
<ul>
  <li> <%= band.name %> </li>
  <a href="<%= edit_band_url(band) %>">Edit this Band</a>
  <form action="<%=  band_url(band) %>" method="post">
    <input type="hidden" name="_method" value="delete">
    <%= authentication %>"
    <input type="submit" value="Delete Account">
  </form>
</ul>

W4D5/MusicApp/app/views/bands/edit.html.erb
<h1>Edit That Band!</h1>

<%= render "form", band: @band, type: :edit%>

W4D5/MusicApp/app/views/bands/index.html.erb
<h1>ALL the bands</h1>
<ul>
  <% @bands.each do |other_band| %>
    <li>
      <%= render 'band', band: other_band %>
    </li>
    <br>
  <% end %>
</ul>

W4D5/MusicApp/app/views/bands/new.html.erb
<h1>Make that Band!</h1>

<%= render "form", band: @band, type: :new %>

W4D5/MusicApp/app/views/bands/show.html.erb
<!-- <h1>Imma show you a band</h1> -->
<div id='container'>
      <p> BAND! </p>

      <p>Bandname: <%= @band.name %></p>


      <p> <%= render 'band', band: @band %> </p>
      <p><a href='<%= bands_url %>'>Back to the Bands!</a> </p>
  </div>

W4D5/MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <h1 class='underline'>MUSIC APP HEADER</h1>
  <br><br>
  <body>
    <%= yield %>
  </body>
</html>

W4D5/MusicApp/app/views/users/_form.html.erb
<% if type == :new %>
  <% button_val = "Create!" %>
  <% action_url = users_url %>
<% elsif type == :edit %>
  <% button_val = "Edit!" %>
  <% action_url = user_url %>
<%elsif type == :login %>
  <% button_val = "Login" %>
  <% action_url = session_url %>
<% end %>


<form action="<%= action_url %>" method="post">
  <% if type == :edit %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <%= authentication %>


  <label for='username'>Username:</label>
  <input type="text" id="username" name="user[username]"
    value="<%=user.username %>">
  <br>

  <label for="password">Password:</label>
  <input type="password" id="password" name="user[password]">
  <br>

  <label for="email">Email:</label>
  <input type="text" id="email" name="user[email]">
  <br>

  <input type="submit" value="<%= button_val %>">

</form>

W4D5/MusicApp/app/views/users/_user.html.erb
<ul>
  <li> <%= user.username %> </li>
  <a href="<%= edit_user_url(user) %>">Edit this User</a>
  <form action="<%=  user_url(user) %>" method="post">
    <input type="hidden" name="_method" value="delete">
    <%= authentication %>"
    <input type="submit" value="Delete Account">
  </form>
</ul>

W4D5/MusicApp/app/views/users/edit.html.erb
<h1>Edit That User!</h1>

<%= render "form", user: @user, type: :edit%>

W4D5/MusicApp/app/views/users/index.html.erb
<h1>ALL the users</h1>
<ul>
  <% @users.each do |other_user| %>
    <li>
      <p><%= user_interaction(other_user) %></p>
      <%= render 'user', user: other_user %>
    </li>
    <br>
  <% end %>
</ul>

W4D5/MusicApp/app/views/users/new.html.erb
<h1>Make that User!</h1>

<%= render "form", user: @user, type: :new %>

W4D5/MusicApp/app/views/users/show.html.erb
<!-- <h1>Imma show you a user</h1> -->
<div id='container'>
      <p> WELCOME! </p>

      <p>Username: <%= @user.username %></p>

      <p>Email: <%= @user.email %> </p>

      <p> <%= render 'user', user: @user %> </p>
      <p><a href='<%= users_url %>'>Back to the Users!</a> </p>
  </div>